---
### This tasks file downloads Nagios source code, configures, compiles and installs it on this monitoring server
- name: Download the source code for a release of Nagios Core and extract it
  unarchive:
    src: "{{ nagios_dwld_url }}"
    dest: "/home/{{ vm_user }}"
    copy: no
  tags:
    - dwld_nagios

- name: Configure Nagios
  command: ./configure --with-nagios-group={{ nagios_group }} --with-command-group={{ nagcmd_group }}
  args:
    chdir: "/home/{{ vm_user }}/nagios-{{ nagios_version }}"
  tags:
    - cfg_nagios

- name: Compile Nagios
  command: "{{ item }}"
  args:
    chdir: "/home/{{ vm_user }}/nagios-{{ nagios_version }}"
  with_items:
    - make clean
    - make all
    - make install
    - make install-commandmode
    - make install-init
    - make install-config
    - /usr/bin/install -c -m 644 sample-config/httpd.conf /etc/apache2/sites-available/nagios.conf
  tags:
   - cfg_nagios

- name:  Add the web server user to the group
  user: name=www-data group="{{ nagcmd_group }}"
  tags:
    - web_user