---
### This task file downloads Nagios-plugins, configures and compiles it
- name: Download the source code for a release of Nagios-plugins and extract it
  unarchive:
    src: "{{ plugin_dwld_url }}"
    dest: "/home/{{ vm_user }}"
    copy: no
  tags:
    - dwld_nagios_plugin

- name: Configure Nagios-plugins
  command: ./configure --with-nagios-user={{ user }} --with-nagios-group={{ nagios_group }} --with-openssl
  args:
    chdir: "/home/{{ vm_user }}/nagios-plugins-{{ plugin_version }}"
  tags:
    - cfg_nagios_plugin

- name: Compile Nagios-plugins
  command: "{{ item }}"
  args:
    chdir: "/home/{{ vm_user }}/nagios-plugins-{{ plugin_version }}"
  with_items:
    - make
    - make install
  tags:
   - cfg_nagios_plugin